### ISSUE TITLE
Solar Panels / World Does Not Have Skylight

### ISSUE THREAD

**Issue by MCEventHorizon** [UnRealDinnerbone/JAMD#1]
For example, mekanism wind and solar generators don't work.

**Comment by UnRealDinnerbone** [comment]
The point of the Mining Dimension it to mine ores and not build a base there that the reason that solar panels and other generators that need the sky / light level don't work there

**Comment by MCEventHorizon** [comment]
Would it be possible to add a config for this? Cause people on my server, for example, would like to use these generators to power their quarries.

**Comment by UnRealDinnerbone** [comment]
I think by using a data pack and changing the has_skylight boolean  https://github.com/UnRealDinnerbone/JAMD/blob/main/src/main/resources/data/jamd/dimension_type/mining.json 
it might work

**Comment by UnRealDinnerbone** [comment]
Should note this might cause issues so be carefull

**Comment by MCEventHorizon** [comment]
Alright, thanks.

**Comment by Mig979** [comment]
@MCEventHorizon did you ever get this working? I tried making a data pack but it's not working for me.

**Comment by UnRealDinnerbone** [comment]
So the issue is the way the isDaytime() is checked is a bit weird for some reason if your world has a fixed time (Like the Void world does) it returns false. I could change this with a Mixin but I prefer not to. (Will have an update later on what I will do about this)

**Comment by UnRealDinnerbone** [comment]
Looking the way to "fix" this would be to change the "fixed_time" in data/javd/dimension_type/void.json to false, only down side would be that the  world have a daylight cycle then

**Comment by MCEventHorizon** [comment]
> 
> 
> @MCEventHorizon did you ever get this working? I tried making a data pack but it's not working for me.

I didn't :/

**Comment by UnRealDinnerbone** [comment]
Well after thinking about I really don't want to mixin into the check for this so if you really want to be able to use stuff that calls isDaytime() change "fixed_time" in data/jamd/dimension_type/mining.json  to false

**Comment by Mig979** [comment]
I tried this and it works but as said above the world now has a daylight cycle, tried changing that with "/gamerule doDaylightCycle false" which works but unfortunately changes the overworld as well. Thanks for looking into it! @UnRealDinnerbone

**Comment by MCEventHorizon** [comment]
Would it be possible to add this to the config(I mean enabling skylight, even if that turn daylight cycle, that doesn't matter to me)?

**Comment by Mig979** [comment]
[jamd-datapack.zip](https://github.com/UnRealDinnerbone/JAMD/files/5817310/jamd-datapack.zip)

There you go, just drop it on your world's "datapacks" folder, only changes I made was settings "has_skylight" to "true" and remove the "fixed_time" line as setting it to "false" seems to actually set it to "0" which wouldn't fix the issue, you will now have a daylight cycle however. I hope that helps.

**Comment by UnRealDinnerbone** [comment]
Removing the line it self might work

**Comment by MCEventHorizon** [comment]
> 
> 
> [jamd-datapack.zip](https://github.com/UnRealDinnerbone/JAMD/files/5817310/jamd-datapack.zip)
> 
> There you go, just drop it on your world's "datapacks" folder, only changes I made was settings "has_skylight" to "true" and remove the "fixed_time" line as setting it to "false" seems to actually set it to "0" which wouldn't fix the issue, you will now have a daylight cycle however. I hope that helps.

Thanks!

**Comment by Joly0** [comment]
I cant get the datapack to work for 1.18.2. Can someone maybe provide me a datapack for 1.18.2 with the default values except the time being set to 6000 and the skylight enabled?
