### ISSUE TITLE
error with currently selected data packs

### ISSUE THREAD

**Issue by Winkletron** [UnRealDinnerbone/JAMD#10]
JAMD is causing me to not be able to load my world and giving me this error "Errors in currently selected datapacks prevented world from loading. You can either try to load only with vanilla datapack ("safe mode") or go back to title screen and fix it manually. ... You can either try to load it with only the vanilla data pack ("safe mode"), or go back to the title screen and fix it manually."

I know it is JAMD that causes it cause when I remove the mod from my folder the game loads fine

**Comment by UnRealDinnerbone** [comment]
Does the mod work by it self and if so what other mods are in the pack?

**Comment by Winkletron** [comment]
The mod works fine by itself here is an image of my mods folder

![mods folder](https://user-images.githubusercontent.com/79426131/108763481-54297e80-7549-11eb-96be-db957263a21b.png)

**Comment by UnRealDinnerbone** [comment]
I dont want to go through each mod, but I suggest testing with any mod that does world stuff
