### ISSUE TITLE
Bug with JAMD-1.1.9-beta+mc-1.16.5

### ISSUE THREAD

**Issue by Erb69** [UnRealDinnerbone/JAMD#12]
In newest MOD pack Direwolf20 the mining dimension now says "Invalid world ID set" when you try to enter.  I experimented copying the JAMD-1.1.4-beta+mc-1.16.4.jar file to the new Direwolf20 modpack (Minecraft version 1.16.5) instance. When I went through it brought me to "The Undergarden". Looks like the two mods used the same world ID.

**Comment by UnRealDinnerbone** [comment]
This is a bug with Minecraft, https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/99
