### ISSUE TITLE
More 2 questions really

### ISSUE THREAD

**Issue by IamStig** [UnRealDinnerbone/JAMD#15]
Is it possible to have clouds turned off by default (just in the mining DIM)?
Have you disabled solar power generating in the dim (is there a config option to enable it)

The problem with clouds is the top of the Mining dim surface is above the clouds, bit annoying.
I made a Powah solar panel and tested it in the overworld, took it to the Mining dim and nada.

**Comment by UnRealDinnerbone** [comment]
Clouds are a set thing. I have another mod that I need to publish that lets you change cloud height.
Question two is same as #1
