### ISSUE TITLE
Misbehaving datapack property 

### ISSUE THREAD

**Issue by Bilal2453** [UnRealDinnerbone/JAMD#18]
Over [here](https://github.com/UnRealDinnerbone/JAMD/blob/main/src/main/resources/data/jamd/dimension_type/mining.json#L6) `has_skylight` is being set to `false`, which is quite the opposite of what it should be when the dimension is always day (that's a `true` value). This results in many other mods misbehaving inside of the dimension when they do require skylight.

One small example is the Solar Neutron Activator machine from Mekanism, which requires skylight to operate. I am assuming here this wasn't intentionally set to prevent those mods from working, because it would be pretty much one of the worst ways of doing it imo.

**Comment by UnRealDinnerbone** [comment]
Same as #1

**Comment by UnRealDinnerbone** [comment]
Yes, I set it that way because I don't want people making bases in the mining dimension. Sadly there some cases where it would be nice but if you want it the other way you can change it

**Comment by Bilal2453** [comment]
I see. Can't say a lot other than fair enough I guess, *time to move my reactor :)*. Thanks.

**Comment by Bilal2453** [comment]
Oh just got to check the closed issues, and looks like this isn't the only nor the second one about this. Therefor I think there actually should be a bit of warning about it, for example the first time you enter the dimension it would post a welcoming message into the player's chat, that also explains this behavior. Or something similar to that, just so it is more clear for people and repo doesn't get spammed just about this.
