### ISSUE TITLE
Adjusting terrain height?

### ISSUE THREAD

**Issue by InsaneJ** [UnRealDinnerbone/JAMD#2]
The terrain seems to generate up to around Y-level 132. This causes the first 60 or so layers to be mostly stone with nothing of interest in it.

Is there a way to adjust the height for the terrain?

Looking through the data pack here:
https://github.com/UnRealDinnerbone/JAMD/blob/main/src/main/resources/data/jamd/dimension_type/mining.json
there doesn't seem to be an option for this?

**Comment by UnRealDinnerbone** [comment]
Change noise.height  in data/jamd/worldgen/noise_settings/mining.json the top of the world will be about 1/2 of that value

**Comment by InsaneJ** [comment]
That did the trick. Thanks!
