### ISSUE TITLE
Add Ability to edit the dimension ID

### ISSUE THREAD

**Issue by prossberg** [UnRealDinnerbone/JAMD#20]
I would love to exclude this dimension from my shaderpack but jamd and mining don't work as dimension IDs. I would like to be able to edit the dimension ID through the config file.

**Comment by UnRealDinnerbone** [comment]
It is not possible to edit with a config file do it how there loaded (with datpacks) 
to find the right dim id do /execute in (press tab) that should give you a list of all dim id
