### ISSUE TITLE
Invalid World  ID set

### ISSUE THREAD

**Issue by EddyBuhler** [UnRealDinnerbone/JAMD#24]
Using MC 1.18.1, with both Terralith 2.0 and Bioms O'Plenty. Although I had this issue with only Terralith, too.

When I create the mining portal block, either on rightclicking it TO the mining dimension, or on trying to return FROM the mining dimension, I get an error "invalid world id set".

**Comment by UnRealDinnerbone** [comment]
make sure you on the latest version, and you might have to replace portals after update

**Comment by EddyBuhler** [comment]
I'm on 1.4.3 build 21 and made a new world, got this on the first portal block I created.

**Comment by lawfulrocky** [comment]
i am having the same problem. i am on the lastest one too i using Terralith 2.0 and Biomes  O'Pleanty

**Comment by UnRealDinnerbone** [comment]
New Forge on Curseforge

**Comment by ofseaandstars** [comment]
I am getting this same issue, even on the latest Forge version.

JAMD version: JAMD-1.5.0-build.22+mc1.18.1
Forge version: 39.0.75 (Client and Server)

Quick update: I'm also not seeing a dimensions folder for JAMD be generated at all.

Update 2: Testing with my pack, it appears to only affect my server. Creating a new world and placing a portal generates the dimension as expected. Joining a server with the exact same pack and trying to interact with the portal shows the above error message.

Update 3: This apparently worked when generating a new world on the server. The world created on the 39.0.66 version of forge would not create the dimension, no matter what.
