### ISSUE TITLE
Question: JAMD 1.18

### ISSUE THREAD

**Issue by penturt** [UnRealDinnerbone/JAMD#25]
Mod does not show up on GDLauncher when looking to add mods, any idea why, all other mods seem to be appearing, and if i try for 1.16 it works, just not for 1.18.

**Comment by Bass2style** [comment]
same, it's buggy, i think it's the "compatibility tag" on curseforge, because the API make the difference between 1.18 and 1.18.1, UnrealDinnerbone need to set the mod compatible with 1.18.1 on CurseForge to make it visible on most of launchers.

**Comment by UnRealDinnerbone** [comment]
New Forge on Curseforge
