### ISSUE TITLE
[1.18.1] compatibility with Forge 39.0.44+

### ISSUE THREAD

**Issue by Bass2style** [UnRealDinnerbone/JAMD#26]
Hi,

the mod seems no more compatible with forge 39.0.44 and up due to this change : 
 - 39.0.45 Remove references to the now-broken `BlockEntity#save(CompoundTag)` method (#8235)
that come due to this one if i'm correct : 
 - 39.0.44 update McModLauncher libraries to newer versions...
 
 it's possible to update the mod to the latest forge please ? (and set it compatible with 1.18_.1_ on CurseForge. xD)
 
 if the code of both are the same, JAVD could be also affected by those changes. (and is also affected by the CurseForge request.)

have a nice day.

edit : not sure if it's pertinent, because it's a forge compatibility issue, but here is a crashlog that happens when you try to load a previously created world on a 55+ Forge world with JAMD : https://gist.github.com/Bass2style/e448a85a159db76b9d11764471360ea2

**Comment by UnRealDinnerbone** [comment]
New Forge on Curseforge
