### ISSUE TITLE
Error Getting Mining Dimension

### ISSUE THREAD

**Issue by ghost** [UnRealDinnerbone/JAMD#27]
**Error Getting Mining Dimension**

![unknown](https://user-images.githubusercontent.com/54646457/155027286-76de9995-816e-4ec4-b69d-716472ea53fd.png)

**Comment by UnRealDinnerbone** [comment]
What version of the mod are you on, and what other mods are in the pack

**Comment by ghost** [comment]
> What version of the mod are you on, and what other mods are in the pack

Modpack TNP5 v0.18.0

**Comment by jorygo** [comment]
I'm also seeing this issue. I'm playing on the AQM3 modpack (Another Quality Modpack 3) v1.5.3 (the modlist is long). The version of JAMD is "JAMD-1.6.0-build.23+mc1.18.1.jar"

For reference, in my case the world was updated from a previous version of the mod. Any of the mining dimensions that were generated before the update have this error. For testing I started a new world and was able to successfully load the mining dimension, but on the server I'm playing on as well as a single-player world I had created before the update I get the error mentioned above.

As a side note: I tried deleting the jamd folder in the hopes it would regenerate and fix the issue, but it does not do that. No new folder, and still gets this error when I try and use the mining portal.

**Comment by johnson32414** [comment]
also having this issue, has been a while since the original post. any fix on it ?

**Comment by theraspb3rry** [comment]
> As a side note: I tried deleting the jamd folder in the hopes it would regenerate and fix the issue, but it does not do that. No new folder, and still gets this error when I try and use the mining portal.

I just did exactly this and obviously the old mining dimension was gone but I just spawned peoples stuff back in and started mining again. The specific folder that i deleted was `world/dimensions/jamd`
