### ISSUE TITLE
Chunkloading doesn't seem to be working

### ISSUE THREAD

**Issue by aerialspring** [UnRealDinnerbone/JAMD#28]
JAMD v1.60-build23+mc1.18.1
FTB chunks v 1801.3.4-build.127
Forge 39.0.88

Using FTB chunks to chunkload an area in the mining dim as well as base in OW. RFTools builder with quarry card, and the entire area is chunkloaded including the builder. Outputting to ender chest, and pulling from enderchest at base (not vanilla one - ender storage ones). While standing in mining dim, quarry is going and items are being output to chest, and I can see they are being pulled out at the other end. Going back to base in OW, i can see items in the chest being pulled out and items being put in, but after about 10 seconds, it stops and nothing new enters the chest. 

Repeatable - every time I go back to mining dim, it works again. Going back to OW it works for about 10 seconds and then stops, even though both areas are fully chunk loaded.

**Comment by UnRealDinnerbone** [comment]
https://github.com/FTBTeam/FTB-Mods-Issues/issues/200
