### ISSUE TITLE
[1.18.2] Bigger Stacks + JAMD cross mod crash

### ISSUE THREAD

**Issue by PokeMaserJ** [UnRealDinnerbone/JAMD#29]
https://github.com/PORTB/BiggerStacks/issues/6

**Comment by UnRealDinnerbone** [comment]
I do not support this mod

**Comment by PokeMaserJ** [comment]
Can you explain why? What's the issue with it?

**Comment by UnRealDinnerbone** [comment]
Because that mod is very hacky mixins, witch cause others mod to break that do nothing wrong
