### ISSUE TITLE
Blacklist For Ores

### ISSUE THREAD

**Issue by Nemesisfromdiscord** [UnRealDinnerbone/JAMD#3]
How can I prevent any ore from spawning? I don't see a blacklist setting anywhere.

**Comment by UnRealDinnerbone** [comment]
Since the way the worlds work now with Minecraft, I cant easily add a config for it. I would suggest using KubeJS to remove the ores you don't want ( https://mods.latvian.dev/books/kubejs/page/worldgenremoveeventjs )
