### ISSUE TITLE
Question: Can I somehow make mobs spawn in the mining dimension? 

### ISSUE THREAD

**Issue by TeeJay1306** [UnRealDinnerbone/JAMD#35]
I saw that there is no shadow in the mining dimension.
Is it still possible to somehow make mobs spawn there, like they would in the overworld
![2022-07-29_18 47 23](https://user-images.githubusercontent.com/56026689/181806553-ac5d889c-fc64-481a-9c36-d07c0af7da44.png)
?

**Comment by UnRealDinnerbone** [comment]
This can be done by editing the json files with a datapack https://github.com/UnRealModding/JAMD/blob/1.18/src/main/resources/data/jamd/worldgen/biome/mining.json
Use to see how to add stuff
https://misode.github.io/worldgen/biome/
