### ISSUE TITLE
Hostile mobs cant spawn with  a mob farm : /

### ISSUE THREAD

**Issue by Leclowndu93150** [UnRealDinnerbone/JAMD#36]
Soo i know that this is a mining dim and it was made to mine ores BUT people with a potato pc who cant run the overworld with more than 10 fps have no fucking choice and thats why i made my base there.
It would be cool if you could add more configs to tweak it

**Comment by UnRealDinnerbone** [comment]
This can be done by editing the json files with a datapack https://github.com/UnRealModding/JAMD/blob/1.18/src/main/resources/data/jamd/worldgen/biome/mining.json
Use to see how to add stuff
https://misode.github.io/worldgen/biome/
