### ISSUE TITLE
[1.18.2] generation issue.

### ISSUE THREAD

**Issue by Bass2style** [UnRealDinnerbone/JAMD#38]
Hi,

idk if you still support 1.18.x because the 1.19 is out, but i have a weird issue.

when i generate the dimension, i only have grass/dirt/stone/deepslate, and no ores at all. this wasn't happening before.

i think it's a conflict with a mod somewhere, because JAMD worked before, but, i did a lot of mod updates recently, and it's nearby impossible to find out what mod is breaking JAMD.

i tryed to rollback JAMD Version to build 24, and deleting the dimension folder, but same result on both versions.

i found nothing in my latest.log, but you can find it here : https://gist.githubusercontent.com/Bass2style/02caff45fe3ed1171bad4f379c4cb346/raw/11fd4b0ce25838889b089c09c79502cb6b19c8e8/gistfile1.txt

Jamd Version : 1.7.0 Build 24 and 25 (both aren't working anymore)
Forge Version : 40.1.76 (should that comme from Forge ? i used a very older version before updating iirc.)

have a nice day.

**Comment by reDBo0n** [comment]
Got the same problem and enabled/disabled all of my mods until I think I found the problem.
If Terrblender is active the Mining Dimension doesn't spawn any ores.
I can use any other mod I have in my pack except it (and BYG, because it has a dependency to it)

EDIT: Just downgraded TerraBlender to 1.18.2-1.1.0.102 and now ore started to spawn.

**Comment by Bass2style** [comment]
thanks for doing the job i didn't do. xD i'm downgrading TerraBlender asap then. thanks for your help.

edit : downgrading TerraBlender fixed it, thanks.
i think i'm going to remove TB and his dependencies, on the TerraBlender Git, we can't report 1.18 related bugs because they stopped the support of 1.18.x (lul) and some other mods seems affected (RFTDimensions for example) also with other versions. RIP

marking this as resolved. o/

**Comment by UnRealDinnerbone** [comment]
Make sure to report the issue the TerraBlender
