### ISSUE TITLE
Dimension changes cause a block desync

### ISSUE THREAD

**Issue by robotgryphon** [UnRealDinnerbone/JAMD#39]
Mod Version: 1.12.0 (Aug 8)
Forge: 43.1.25

Using the portal works as expected, teleporting the user to the dimension and back, but upon arrival the portal block is erroneously placed a a different location than it's supposed to be. This appears to be a ghost block; right clicking it in the overworld causes it to disappear.

See below, of the block "replacing" a digital miner until a relog:

![2022-09-20_18 28 49](https://user-images.githubusercontent.com/8529636/191376314-13192a13-ff0c-45b7-be7b-8097cffdf95c.png)
![2022-09-20_18 27 10](https://user-images.githubusercontent.com/8529636/191376315-8fb1f496-237d-4f32-9a85-d0ab3d59ef45.png)

**Comment by UnRealDinnerbone** [comment]
This issue should be fixed in version 2.0.0
