### ISSUE TITLE
Invalid world ID set

### ISSUE THREAD

**Issue by attrib** [UnRealDinnerbone/JAMD#5]
After upgrading to 1.16.5 using JAMD-1.1.6-beta+mc-1.16.5 (FTB Presents Direwolf20 1.16 - 1.6.0) I get the error "Invalid world ID set" in chat when clicking on the mining portal block.

The latest and debug logs doesn't have any further information.

The <save>/dimensions/jamd folder also exists and has content.

What else would you need for further debugging?

**Comment by UnRealDinnerbone** [comment]
https://github.com/UnRealDinnerbone/JAVD/issues/16#issuecomment-773353918 (How to fix, I have not tested)
This is how is fixed the for void world, no idea what is making this happen, should not be me as the mods where not updated in that update.

**Comment by UnRealDinnerbone** [comment]
This is most likely due to how Unstable dimensions are in 1.16.3+ I really don't know what I can do about it.
 I should fix that message through in-game as it clearly saying witch part is an error in the code.

**Comment by attrib** [comment]
Just to confirm, fix from https://github.com/UnRealDinnerbone/JAVD/issues/16#issuecomment-773353918 works for JAMD as well.

**Comment by UnRealDinnerbone** [comment]
thanks
