### ISSUE TITLE
No actual Mining Dimension?

### ISSUE THREAD

**Issue by FryoKnight** [UnRealDinnerbone/JAMD#6]
Recently moved to Minecraft 1.16.5, and have no clue about how to do Datapacks, and was hoping to find a mod that could simply add in a proper mining dimension in our server.

But there doesn't seem to be any example Datapack for your mod as stated on the CurseForge page to properly ass it in?
Please help?

**Comment by UnRealDinnerbone** [comment]
It here https://github.com/UnRealDinnerbone/JAMD/tree/main/src/main/resources/data/jamd
Also updated the Readme to show where it is
