### ISSUE TITLE
question on the dimension name if I were to add some more resources to the mining dimension as I'm stupid when it comes to datapacks

### ISSUE THREAD

**Issue by Algester** [UnRealDinnerbone/JAMD#7]
for example with Astral Sorcery it has a config to add its resources to a dimension (while true I can just say let it generate in all worlds but that would also be "silly" to have some none nether resources pop up in the nether thing is it is using the dimension string name to spawn those resources in this case what is the dimension string name is it just "mining" or "JAMD"?

**Comment by UnRealDinnerbone** [comment]
the id of the world is "jamd:mining" the name should just be "mining"
