### ISSUE TITLE
Adding ore to the world

### ISSUE THREAD

**Issue by Goten87** [UnRealDinnerbone/JAMD#8]
How do i add ores to the mining dim is that true the the datapack `data/jamd/worldgen/biome/mining.json` and adding the ore in the features array or do i need to do something else for it

**Comment by UnRealDinnerbone** [comment]
yes all you should need to do is add it the array

**Comment by Goten87** [comment]
i want to add clay blocks to the mining world is this correct then for it
```json
"features": [
    [
      "minecraft:ore_gravel",
      "minecraft:ore_granite",
      "minecraft:ore_diorite",
      "minecraft:ore_andesite",
      "minecraft:ore_coal",
      "minecraft:ore_iron",
      "minecraft:ore_gold",
      "minecraft:ore_redstone",
      "minecraft:ore_diamond",
      "minecraft:ore_lapis",
      "minecraft:ore_emerald",
      "minecraft:clay"
    ]
``` 
sins when i dont have the normal ores in that array its not spawning them at all in the mineworld
