### ISSUE TITLE
Lighting issues with shaders

### ISSUE THREAD

**Issue by MJRamon** [UnRealDinnerbone/JAMD#9]
Dimension has lighting issues when using shaders - ground is non-lit and dimmed, sky is looking fine.

Minecraft 1.16.4
Forge 35.1.37
OptiFine_1.16.4_HD_U_G6
OptiForge-MC1.16.4-0.4.6
JAMD-1.1.6-beta+mc-1.16.5
Shaders: Sildurs Vibrant Shaders v1.283 Lite

Setting
```
"has_skylight": true,
```
did not help.

**Comment by UnRealDinnerbone** [comment]
I do not support Optifine

**Comment by MJRamon** [comment]
That's a shame, cause yet millions of people use it.
Thanks, I guess.
